export const COUNTRIES: { code: string; name_ru: string; name_en: string }[] = [
  { code: "KAZ", name_ru: "Казахстан", name_en: "Kazakhstan" },
  { code: "RUS", name_ru: "Россия", name_en: "Russia" },
  { code: "KGZ", name_ru: "Кыргызстан", name_en: "Kyrgyzstan" },
  { code: "UZB", name_ru: "Узбекистан", name_en: "Uzbekistan" },
  { code: "TJK", name_ru: "Таджикистан", name_en: "Tajikistan" },
  { code: "TKM", name_ru: "Туркменистан", name_en: "Turkmenistan" },
  { code: "AZE", name_ru: "Азербайджан", name_en: "Azerbaijan" },
  { code: "ARM", name_ru: "Армения", name_en: "Armenia" },
  { code: "GEO", name_ru: "Грузия", name_en: "Georgia" },
  { code: "BLR", name_ru: "Беларусь", name_en: "Belarus" },
  { code: "UKR", name_ru: "Украина", name_en: "Ukraine" },
  { code: "MDA", name_ru: "Молдова", name_en: "Moldova" },
  { code: "AFG", name_ru: "Афганистан", name_en: "Afghanistan" },
  { code: "ALB", name_ru: "Албания", name_en: "Albania" },
  { code: "AND", name_ru: "Андорра", name_en: "Andorra" },
  { code: "AGO", name_ru: "Ангола", name_en: "Angola" },
  { code: "ARG", name_ru: "Аргентина", name_en: "Argentina" },
  { code: "AUS", name_ru: "Австралия", name_en: "Australia" },
  { code: "AUT", name_ru: "Австрия", name_en: "Austria" },
  { code: "BHS", name_ru: "Багамы", name_en: "Bahamas" },
  { code: "BHR", name_ru: "Бахрейн", name_en: "Bahrain" },
  { code: "BGD", name_ru: "Бангладеш", name_en: "Bangladesh" },
  { code: "BEL", name_ru: "Бельгия", name_en: "Belgium" },
  { code: "BLZ", name_ru: "Белиз", name_en: "Belize" },
  { code: "BEN", name_ru: "Бенин", name_en: "Benin" },
  { code: "BTN", name_ru: "Бутан", name_en: "Bhutan" },
  { code: "BOL", name_ru: "Боливия", name_en: "Bolivia" },
  { code: "BIH", name_ru: "Босния и Герцеговина", name_en: "Bosnia and Herzegovina" },
  { code: "BWA", name_ru: "Ботсвана", name_en: "Botswana" },
  { code: "BRA", name_ru: "Бразилия", name_en: "Brazil" },
  { code: "BRN", name_ru: "Бруней", name_en: "Brunei" },
  { code: "BGR", name_ru: "Болгария", name_en: "Bulgaria" },
  { code: "BFA", name_ru: "Буркина-Фасо", name_en: "Burkina Faso" },
  { code: "BDI", name_ru: "Бурунди", name_en: "Burundi" },
  { code: "CPV", name_ru: "Кабо-Верде", name_en: "Cabo Verde" },
  { code: "KHM", name_ru: "Камбоджа", name_en: "Cambodia" },
  { code: "CMR", name_ru: "Камерун", name_en: "Cameroon" },
  { code: "CAN", name_ru: "Канада", name_en: "Canada" },
  { code: "CAF", name_ru: "ЦАР", name_en: "Central African Republic" },
  { code: "TCD", name_ru: "Чад", name_en: "Chad" },
  { code: "CHL", name_ru: "Чили", name_en: "Chile" },
  { code: "CHN", name_ru: "Китай", name_en: "China" },
  { code: "COL", name_ru: "Колумбия", name_en: "Colombia" },
  { code: "COM", name_ru: "Коморы", name_en: "Comoros" },
  { code: "COD", name_ru: "ДРК", name_en: "DR Congo" },
  { code: "COG", name_ru: "Конго", name_en: "Congo" },
  { code: "CRI", name_ru: "Коста-Рика", name_en: "Costa Rica" },
  { code: "CIV", name_ru: "Кот-д'Ивуар", name_en: "Côte d'Ivoire" },
  { code: "HRV", name_ru: "Хорватия", name_en: "Croatia" },
  { code: "CUB", name_ru: "Куба", name_en: "Cuba" },
  { code: "CYP", name_ru: "Кипр", name_en: "Cyprus" },
  { code: "CZE", name_ru: "Чехия", name_en: "Czech Republic" },
  { code: "DNK", name_ru: "Дания", name_en: "Denmark" },
  { code: "DJI", name_ru: "Джибути", name_en: "Djibouti" },
  { code: "DOM", name_ru: "Доминиканская Республика", name_en: "Dominican Republic" },
  { code: "ECU", name_ru: "Эквадор", name_en: "Ecuador" },
  { code: "EGY", name_ru: "Египет", name_en: "Egypt" },
  { code: "SLV", name_ru: "Сальвадор", name_en: "El Salvador" },
  { code: "GNQ", name_ru: "Экваториальная Гвинея", name_en: "Equatorial Guinea" },
  { code: "ERI", name_ru: "Эритрея", name_en: "Eritrea" },
  { code: "EST", name_ru: "Эстония", name_en: "Estonia" },
  { code: "SWZ", name_ru: "Эсватини", name_en: "Eswatini" },
  { code: "ETH", name_ru: "Эфиопия", name_en: "Ethiopia" },
  { code: "FJI", name_ru: "Фиджи", name_en: "Fiji" },
  { code: "FIN", name_ru: "Финляндия", name_en: "Finland" },
  { code: "FRA", name_ru: "Франция", name_en: "France" },
  { code: "GAB", name_ru: "Габон", name_en: "Gabon" },
  { code: "GMB", name_ru: "Гамбия", name_en: "Gambia" },
  { code: "DEU", name_ru: "Германия", name_en: "Germany" },
  { code: "GHA", name_ru: "Гана", name_en: "Ghana" },
  { code: "GRC", name_ru: "Греция", name_en: "Greece" },
  { code: "GTM", name_ru: "Гватемала", name_en: "Guatemala" },
  { code: "GIN", name_ru: "Гвинея", name_en: "Guinea" },
  { code: "GNB", name_ru: "Гвинея-Бисау", name_en: "Guinea-Bissau" },
  { code: "GUY", name_ru: "Гайана", name_en: "Guyana" },
  { code: "HTI", name_ru: "Гаити", name_en: "Haiti" },
  { code: "HND", name_ru: "Гондурас", name_en: "Honduras" },
  { code: "HUN", name_ru: "Венгрия", name_en: "Hungary" },
  { code: "ISL", name_ru: "Исландия", name_en: "Iceland" },
  { code: "IND", name_ru: "Индия", name_en: "India" },
  { code: "IDN", name_ru: "Индонезия", name_en: "Indonesia" },
  { code: "IRN", name_ru: "Иран", name_en: "Iran" },
  { code: "IRQ", name_ru: "Ирак", name_en: "Iraq" },
  { code: "IRL", name_ru: "Ирландия", name_en: "Ireland" },
  { code: "ISR", name_ru: "Израиль", name_en: "Israel" },
  { code: "ITA", name_ru: "Италия", name_en: "Italy" },
  { code: "JAM", name_ru: "Ямайка", name_en: "Jamaica" },
  { code: "JPN", name_ru: "Япония", name_en: "Japan" },
  { code: "JOR", name_ru: "Иордания", name_en: "Jordan" },
  { code: "KEN", name_ru: "Кения", name_en: "Kenya" },
  { code: "PRK", name_ru: "КНДР", name_en: "North Korea" },
  { code: "KOR", name_ru: "Республика Корея", name_en: "South Korea" },
  { code: "KWT", name_ru: "Кувейт", name_en: "Kuwait" },
  { code: "LAO", name_ru: "Лаос", name_en: "Laos" },
  { code: "LVA", name_ru: "Латвия", name_en: "Latvia" },
  { code: "LBN", name_ru: "Ливан", name_en: "Lebanon" },
  { code: "LSO", name_ru: "Лесото", name_en: "Lesotho" },
  { code: "LBR", name_ru: "Либерия", name_en: "Liberia" },
  { code: "LBY", name_ru: "Ливия", name_en: "Libya" },
  { code: "LIE", name_ru: "Лихтенштейн", name_en: "Liechtenstein" },
  { code: "LTU", name_ru: "Литва", name_en: "Lithuania" },
  { code: "LUX", name_ru: "Люксембург", name_en: "Luxembourg" },
  { code: "MDG", name_ru: "Мадагаскар", name_en: "Madagascar" },
  { code: "MWI", name_ru: "Малави", name_en: "Malawi" },
  { code: "MYS", name_ru: "Малайзия", name_en: "Malaysia" },
  { code: "MDV", name_ru: "Мальдивы", name_en: "Maldives" },
  { code: "MLI", name_ru: "Мали", name_en: "Mali" },
  { code: "MLT", name_ru: "Мальта", name_en: "Malta" },
  { code: "MRT", name_ru: "Мавритания", name_en: "Mauritania" },
  { code: "MUS", name_ru: "Маврикий", name_en: "Mauritius" },
  { code: "MEX", name_ru: "Мексика", name_en: "Mexico" },
  { code: "MCO", name_ru: "Монако", name_en: "Monaco" },
  { code: "MNG", name_ru: "Монголия", name_en: "Mongolia" },
  { code: "MNE", name_ru: "Черногория", name_en: "Montenegro" },
  { code: "MAR", name_ru: "Марокко", name_en: "Morocco" },
  { code: "MOZ", name_ru: "Мозамбик", name_en: "Mozambique" },
  { code: "MMR", name_ru: "Мьянма", name_en: "Myanmar" },
  { code: "NAM", name_ru: "Намибия", name_en: "Namibia" },
  { code: "NPL", name_ru: "Непал", name_en: "Nepal" },
  { code: "NLD", name_ru: "Нидерланды", name_en: "Netherlands" },
  { code: "NZL", name_ru: "Новая Зеландия", name_en: "New Zealand" },
  { code: "NIC", name_ru: "Никарагуа", name_en: "Nicaragua" },
  { code: "NER", name_ru: "Нигер", name_en: "Niger" },
  { code: "NGA", name_ru: "Нигерия", name_en: "Nigeria" },
  { code: "MKD", name_ru: "Северная Македония", name_en: "North Macedonia" },
  { code: "NOR", name_ru: "Норвегия", name_en: "Norway" },
  { code: "OMN", name_ru: "Оман", name_en: "Oman" },
  { code: "PAK", name_ru: "Пакистан", name_en: "Pakistan" },
  { code: "PAN", name_ru: "Панама", name_en: "Panama" },
  { code: "PNG", name_ru: "Папуа — Новая Гвинея", name_en: "Papua New Guinea" },
  { code: "PRY", name_ru: "Парагвай", name_en: "Paraguay" },
  { code: "PER", name_ru: "Перу", name_en: "Peru" },
  { code: "PHL", name_ru: "Филиппины", name_en: "Philippines" },
  { code: "POL", name_ru: "Польша", name_en: "Poland" },
  { code: "PRT", name_ru: "Португалия", name_en: "Portugal" },
  { code: "QAT", name_ru: "Катар", name_en: "Qatar" },
  { code: "ROU", name_ru: "Румыния", name_en: "Romania" },
  { code: "RWA", name_ru: "Руанда", name_en: "Rwanda" },
  { code: "SAU", name_ru: "Саудовская Аравия", name_en: "Saudi Arabia" },
  { code: "SEN", name_ru: "Сенегал", name_en: "Senegal" },
  { code: "SRB", name_ru: "Сербия", name_en: "Serbia" },
  { code: "SLE", name_ru: "Сьерра-Леоне", name_en: "Sierra Leone" },
  { code: "SGP", name_ru: "Сингапур", name_en: "Singapore" },
  { code: "SVK", name_ru: "Словакия", name_en: "Slovakia" },
  { code: "SVN", name_ru: "Словения", name_en: "Slovenia" },
  { code: "SOM", name_ru: "Сомали", name_en: "Somalia" },
  { code: "ZAF", name_ru: "ЮАР", name_en: "South Africa" },
  { code: "SSD", name_ru: "Южный Судан", name_en: "South Sudan" },
  { code: "ESP", name_ru: "Испания", name_en: "Spain" },
  { code: "LKA", name_ru: "Шри-Ланка", name_en: "Sri Lanka" },
  { code: "SDN", name_ru: "Судан", name_en: "Sudan" },
  { code: "SUR", name_ru: "Суринам", name_en: "Suriname" },
  { code: "SWE", name_ru: "Швеция", name_en: "Sweden" },
  { code: "CHE", name_ru: "Швейцария", name_en: "Switzerland" },
  { code: "SYR", name_ru: "Сирия", name_en: "Syria" },
  { code: "TWN", name_ru: "Тайвань", name_en: "Taiwan" },
  { code: "TZA", name_ru: "Танзания", name_en: "Tanzania" },
  { code: "THA", name_ru: "Таиланд", name_en: "Thailand" },
  { code: "TLS", name_ru: "Тимор-Лесте", name_en: "Timor-Leste" },
  { code: "TGO", name_ru: "Того", name_en: "Togo" },
  { code: "TTO", name_ru: "Тринидад и Тобаго", name_en: "Trinidad and Tobago" },
  { code: "TUN", name_ru: "Тунис", name_en: "Tunisia" },
  { code: "TUR", name_ru: "Турция", name_en: "Turkey" },
  { code: "UGA", name_ru: "Уганда", name_en: "Uganda" },
  { code: "ARE", name_ru: "ОАЭ", name_en: "United Arab Emirates" },
  { code: "GBR", name_ru: "Великобритания", name_en: "United Kingdom" },
  { code: "USA", name_ru: "США", name_en: "United States" },
  { code: "URY", name_ru: "Уругвай", name_en: "Uruguay" },
  { code: "VEN", name_ru: "Венесуэла", name_en: "Venezuela" },
  { code: "VNM", name_ru: "Вьетнам", name_en: "Vietnam" },
  { code: "YEM", name_ru: "Йемен", name_en: "Yemen" },
  { code: "ZMB", name_ru: "Замбия", name_en: "Zambia" },
  { code: "ZWE", name_ru: "Зимбабве", name_en: "Zimbabwe" },
];
